framework:
  assets:
    json_manifest_path: '%kernel.root_dir%/public/build/manifest.json'
  session:
     handler_id: session.handler.native_file
     save_path: '%kernel.root_dir%/sessions'
parameters:
   locale: nl
